### ISSUE TITLE
Building future version of  Keyboard-color-switcher

### ISSUE THREAD

**Issue by JeffLabonte** [yochananmarqos/pkgbuilds#4]
Hey there!

I wanted to have your help in updating your `PKGBUILD`, but I have no clue where I can add `--recursive-submodules` to the `git clone` command.

Thank you bud for your contributions!

**Comment by yochananmarqos** [comment]
I'm holding off on the PKGBUILD for now until you two get the merge sorted.

**Comment by yochananmarqos** [comment]
It's updated now: https://github.com/yochananmarqos/pkgbuilds/commit/f620bb6136df05a25a2aa0d73422710e97043a77.

**Comment by yochananmarqos** [comment]
I may as well add it to the AUR, eh?

**Comment by JeffLabonte** [comment]
@yochananmarqos I don't feel like it is a piece of software that I would allow people to use yet. I mean, it is still under heavy development.

**Comment by yochananmarqos** [comment]
Fair enough.
