### ISSUE TITLE
pkgbuild / authy - Please upload to aur

### ISSUE THREAD

**Issue by Strykar** [yochananmarqos/pkgbuilds#5]
Would you please upload your authy version that doesn't use the built-in electron to the aur?

**Comment by yochananmarqos** [comment]
Maybe, but what would I call it?

**Comment by Strykar** [comment]
authy-snap or authy-bin?

**Comment by yochananmarqos** [comment]
The original AUR package was called `authy-snap` and it was merged into `authy`. Creating a separate `-bin` package makes no sense as the only release is binary.

It's up to the AUR package maintainer whether he wants to use the bundled or system electron.

**Comment by Strykar** [comment]
The DIscord version that uses system's Electron on the aur is called [discord_arch_electron](https://aur.archlinux.org/packages/discord_arch_electron/), so `authy_arch_electron` perhaps?
IIRC, the current maintainer wants to use the bundled Electron which is why another choice would be great.

**Comment by BachoSeven** [comment]
oftentimes packages in the aur be called `something-no-somethingelse`(like `ffmpeg-no-cuda`), so perhaps `authy-no-electron`?

**Comment by Strykar** [comment]
Yea, authy-no-electron probably makes it clearer.

**Comment by yochananmarqos** [comment]
Good grief... `authy-electron` or `authy-no-electron`? Make up your mind. I'm not adding it to the AUR with a confusing, unconventional name.

**Comment by Strykar** [comment]
authy-no-electron

**Comment by yochananmarqos** [comment]
I added it to the AUR: [`authy-electron`](https://aur.archlinux.org/packages/authy-electron)
