### ISSUE TITLE
Discussion about brightness-controller package

### ISSUE THREAD

**Issue by archisman-panigrahi** [yochananmarqos/pkgbuilds#6]
The package works.
Are `python-cx-freeze` and `python-setuptools` really required?
The source is interpreted by python in runtime, and only the files need to be copied to their proper locations (there is no need to create a standalone executable with python-cx-freeze).

We tried to write the setup.py as an experiment, but it does not work correctly, and we have not been able to implement it properly due to lack of time and knowledge.

Also, since your PKGBUILD works, and the one in AUR does not work, is there any way to transfer the ownership of the AUR package to you?

**Comment by yochananmarqos** [comment]
> Are python-cx-freeze and python-setuptools really required?

No, but it fails without them. See the [`setup.py`](https://github.com/LordAmit/Brightness/blob/master/src/setup.py#L2).

**Comment by archisman-panigrahi** [comment]
What I was trying to say is, setup.py is not required at all.

One only needs to copy the init.py and other .py files to their proper locations.

**Comment by yochananmarqos** [comment]
Right, I could remove that line. I was just using it to generate the `pgkver`.

> is there any way to transfer the ownership of the AUR package to you?

The Maintainer would have to at least add me as a Co-Maintainer. They could also orphan the package and I could adopt it.

**Comment by archisman-panigrahi** [comment]
I don't know the maintainer of the AUR package (he/she is not a developer/co-developer of this app). 
Can I ask them in the AUR webpage to add you as a co-maintainer or transfer the package to you? Is that considered rude in Arch community?

**Comment by yochananmarqos** [comment]
No, that wouldn't be rude since you're a contributor of the upstream project.

**Comment by archisman-panigrahi** [comment]
I have asked the AUR Maintainer to add you as a Co-Maintainer or to orphan it if they cannot maintain it.
I am closing this issue.
