### ISSUE TITLE
theme is not correctly applied to elementary-planner

### ISSUE THREAD

**Issue by archisman-panigrahi** [yochananmarqos/pkgbuilds#7]
OS: Manjaro XFCE stable edition
elementary-planner version: 2.7-1

The AUR package of elementary planner is not following themes correctly (it seems to use adwaita, although that is not even my system theme, and certain elements do not follow the correct theme), and certain fonts are invisible (they are only visible when I select them). I rechecked that `gtk-theme-elementary` is installed in my system, and also tried rebuilding the AUR package.

AUR
![planner-aur](https://user-images.githubusercontent.com/3063132/127440164-008e1737-b4a0-4954-9311-c655d4f91102.png)

Flatpak
![planner-flatpak](https://user-images.githubusercontent.com/3063132/127441519-c5ef1e83-1ee3-4c53-9cf6-82846f329233.png)

 I don't know since when this issue appeared (I last used this app from AUR in another computer in 2020, and back then this issue was absent). `gtk-theme-elementary` was updated quite recently, and I don't know if that update broke planner.

I thought I would let you know before reporting it upstream, since the upstream developer recommends flatpak, and does not seem to entertain installation from other methods.

**Comment by archisman-panigrahi** [comment]
Another bug was reported here https://github.com/alainm23/planner/issues/783, and they are most likely the same.

**Comment by yochananmarqos** [comment]
You'll just have to wait until the developer catches up with Elementary 6 changes or use the Flatpak. I'm just a packager, there's nothing I can do about it.

**Comment by yochananmarqos** [comment]
Downgrading to `gtk-theme-elementary` 5.4.2 and `elementary-icon-theme` 5.3.1 will work. Use `sudo downgrade <package>` and choose the version.

**Comment by ElnuDev** [comment]
I'm getting this issue on the Flatpak on NixOS. (I'd install it from nixpkgs, but the package derivation is currently broken.)
