### ISSUE TITLE
Update for horizontal-grub

### ISSUE THREAD

**Issue by petsam** [yochananmarqos/pkgbuilds#8]
Hi @yochananmarqos . 
I have improved my  [script](https://github.com/yochananmarqos/pkgbuilds/tree/master/horizontal-grub-git) and would like to update it in AUR.

I created a [PKGBUILD](https://gitlab.com/petsam/horizontal-grub/-/raw/master/PKGBUILD) for the latest tag version. If you think it is better to just use a "*-git" version for the AUR (like in your repo), I would not mind. 

I would appreciate for your advice and assistance.

PS:
1. I took the opportunity and moved to [Gitlab](https://gitlab.com/petsam/horizontal-grub).
2. I have worked on a new package (PKGBUILD for supergrub2, not my code) and was wondering if you would like to add it to AUR. 

Greatings.
Petros

**Comment by yochananmarqos** [comment]
Go ahead and adopt the [`horizontal-grub`](https://aur.archlinux.org/packages/horizontal-grub) AUR package if you want.

**Comment by petsam** [comment]
I have no idea how to do that and am not confident yet with pkgbuild .

Would you help me on the first steps?

**Comment by yochananmarqos** [comment]
First see [AUR submission guidelines: Authentication](https://wiki.archlinux.org/title/AUR_submission_guidelines#Authentication) to get setup.

**Comment by yochananmarqos** [comment]
Apparently we both forgot about this. Let me know if you still need help.

**Comment by yochananmarqos** [comment]
Closing as there has been no response.
